FROM node:18.17.0-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY public/ ./public/

COPY src/ ./src/

ARG REACT_APP_API_URL

ENV REACT_APP_API_URL=$REACT_APP_API_URL

RUN npm run build